Repository deskofnoyon/support-system, pull requests merged in 2024-01, with the labels that each got.

#1 feat: intro video section added. update: price section desing update
  index.html
  src/App.jsx
  src/components/intro-video-section/index.jsx
  src/components/navbar/index.jsx
  src/components/price-section/index.jsx
  src/components/price-section/price-plan-card.jsx
  src/components/video-call-section/index.jsx
  tailwind.config.js
Labels: enhancement

#2 update: readme file update
  README.md
Labels: documentation

#4 Rest of the sections completed
  src/App.jsx
  src/assets/arrow.svg
  src/assets/blink.svg
  src/components/faq-section/index.jsx
  src/components/faq-section/question-card.jsx
  src/components/features-section/index.jsx
  src/components/footer/index.jsx
  src/components/intro-video-section/index.jsx
  src/components/navbar/index.jsx
  src/components/navbar/list-item.jsx
  src/components/price-section/price-plan-card.jsx
  src/components/section-title/index.jsx
  src/components/team-section/index.jsx
Labels: enhancement

#6 [FEAT]: Footer section covert to component based
  src/components/footer/footer-link.jsx
  src/components/footer/index.jsx
Labels: enhancement

#8 Shakil/testing
  src/components/testing/index.jsx
Labels: help wanted

#9 Nothing changed just testing via Shakil
  src/components/testing/index.jsx
Labels: help wanted

#11 feat: Update the readme fil with some info
  README.md
Labels: documentation
